export const paymentMethods: {
    value: IndianPaymentMethod;
    label: string;
    icon: string;
}[] = [
    { value: 'cash', label: 'Cash', icon: '💵' },
    { value: 'wallet', label: 'Wallet', icon: '👛' },
    { value: 'upi', label: 'UPI', icon: '📱' },
    { value: 'card', label: 'Card', icon: '💳' },
    { value: 'net_banking', label: 'Net Banking', icon: '🏦' },
];

export const mockPlayers = [
    {
        id: 'p1',
        name: 'Ahmad Hassan',
        email: 'ahmad@email.com',
        phone: '+971 50 123 4567',
    },
    {
        id: 'p2',
        name: 'Sarah Johnson',
        email: 'sarah@email.com',
        phone: '+971 55 234 5678',
    },
    {
        id: 'p3',
        name: 'Mike Chen',
        email: 'mike@email.com',
        phone: '+971 52 345 6789',
    },
    {
        id: 'p4',
        name: 'Fatima Al-Said',
        email: 'fatima@email.com',
        phone: '+971 56 456 7890',
    },
];

export const mockCourts = [
    {
        id: 'c1',
        facility_id: '1',
        name: 'Padel Court 1',
        sport: 'Padel',
        capacity: 4,
        price_per_hour: 150,
        field_size: '20m x 10m',
    },
    {
        id: 'c2',
        facility_id: '1',
        name: 'Padel Court 2',
        sport: 'Padel',
        capacity: 4,
        price_per_hour: 150,
        field_size: '20m x 10m',
    },
    {
        id: 'c7',
        facility_id: '1',
        name: 'Padel Court 3',
        sport: 'Padel',
        capacity: 4,
        price_per_hour: 150,
        field_size: '20m x 10m',
    },
    {
        id: 'c8',
        facility_id: '1',
        name: 'Padel Court 4',
        sport: 'Padel',
        capacity: 4,
        price_per_hour: 150,
        field_size: '20m x 10m',
    },
    {
        id: 'c3',
        facility_id: '1',
        name: 'Pickleball Court 1',
        sport: 'Pickleball',
        capacity: 4,
        price_per_hour: 200,
        field_size: '20m x 10m',
    },
    {
        id: 'c9',
        facility_id: '1',
        name: 'Pickleball Court 2',
        sport: 'Pickleball',
        capacity: 4,
        price_per_hour: 200,
        field_size: '20m x 10m',
    },
    {
        id: 'c10',
        facility_id: '1',
        name: 'Pickleball Court 3',
        sport: 'Pickleball',
        capacity: 4,
        price_per_hour: 200,
        field_size: '20m x 10m',
    },
    {
        id: 'c11',
        facility_id: '1',
        name: 'Pickleball Court 4',
        sport: 'Pickleball',
        capacity: 4,
        price_per_hour: 200,
        field_size: '20m x 10m',
    },
    {
        id: 'c12',
        facility_id: '1',
        name: 'Pickleball Court 5',
        sport: 'Pickleball',
        capacity: 4,
        price_per_hour: 200,
        field_size: '20m x 10m',
    },
    {
        id: 'c13',
        facility_id: '1',
        name: 'Pickleball Court 6',
        sport: 'Pickleball',
        capacity: 4,
        price_per_hour: 200,
        field_size: '20m x 10m',
    },
    {
        id: 'c14',
        facility_id: '1',
        name: 'Pickleball Court 7',
        sport: 'Pickleball',
        capacity: 4,
        price_per_hour: 200,
        field_size: '20m x 10m',
    },
    {
        id: 'c15',
        facility_id: '1',
        name: 'Pickleball Court 8',
        sport: 'Pickleball',
        capacity: 4,
        price_per_hour: 200,
        field_size: '20m x 10m',
    },
    {
        id: 'c16',
        facility_id: '1',
        name: 'Pickleball Court 9',
        sport: 'Pickleball',
        capacity: 4,
        price_per_hour: 200,
        field_size: '20m x 10m',
    },
    {
        id: 'c4',
        facility_id: '2',
        name: 'Padel Court A',
        sport: 'Padel',
        capacity: 4,
        price_per_hour: 120,
        field_size: '20m x 10m',
    },
    {
        id: 'c5',
        facility_id: '2',
        name: 'Tennis Court B',
        sport: 'Tennis',
        capacity: 4,
        price_per_hour: 120,
        field_size: '20m x 10m',
    },
    {
        id: 'c6',
        facility_id: '2',
        name: 'Basketball Court',
        sport: 'Basketball',
        capacity: 10,
        price_per_hour: 180,
        field_size: '28m x 15m',
    },
];

export const paymentMethodDisplayLabels: Record<IndianPaymentMethod, string> = {
    upi: 'UPI',
    cash: 'Cash',
    card: 'Card',
    net_banking: 'Net Banking',
    wallet: 'Wallet',
};
